server {
    listen 80;
    server_name localhost;

    # Permitir subir archivos grandes (ej. 50 Megabytes)
    client_max_body_size 50M;

    root /usr/share/nginx/html;
    index index.html;

    # Soporte para rutas de Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el Backend Spring Boot
    location /api/ {
        proxy_pass http://backend-spring:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    # Proxy para el Microservicio IA (FastAPI/Python)
    location /ia/ {
        proxy_pass http://ia-service:8000/ia/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    # Soporte para WebSockets (Notificaciones en tiempo real)
    location /ws-bpm {
        proxy_pass http://backend-spring:8080/ws-bpm;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
