# ============================================================
#  PERFIL LOCAL - Ejecución en localhost
#  Ejecutar con: mvn spring-boot:run -Dspring-boot.run.profiles=local
#  O con variable: SPRING_PROFILES_ACTIVE=local
# ============================================================

# MongoDB Atlas (misma BD que producción)
spring.data.mongodb.uri=mongodb+srv://davidgcpro18_db_user:nK4eKpyMdpiKXFek@cluster0.knufxuh.mongodb.net/bpm_workflow?retryWrites=true&w=majority&appName=Cluster0

# JWT
jwt.secret=BPM_WORKFLOW_SECRET_KEY_2026_ULTRA_SECURE_256BIT
jwt.expiration=86400000

# Microservicio IA (Cloud Run - Always On)
ia.service.url=https://ia-service-241130514391.us-central1.run.app/ia
